name: test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install codeforces's rust
        uses: dtolnay/rust-toolchain@1.75.0
        with:
          components: rustfmt, clippy

      - name: Print versions
        run: |
          cargo --version
          rustc --version
          cargo clippy --version
          cargo fmt --version

      - name: Prepare build
        run: |
          mkdir build
          echo '<ul><li><a href="./solutions1.pdf">solutions 1</a></li><li><a href="./solutions2.pdf">solutions 2</a></li></ul>' > build/index.html

      - name: Check homework 1 example code
        working-directory: hw1/apples
        run: |
          cargo clippy --verbose -- -Dwarnings
          cargo fmt --check --verbose
          cargo test --verbose
          cargo build --verbose

      - name: Check homework 1 code
        working-directory: hw1/kittens
        run: |
          cargo clippy --verbose -- -Dwarnings
          cargo fmt --check --verbose
          cargo test --verbose
          cargo build --verbose

      - name: Generate homework 1 solutions
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: hw1
          root_file: main.tex

      - name: Generate homework 2 solutions
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: hw2
          root_file: main.tex

      - name: Move solutions
        run: |
          mv hw1/main.pdf build/solutions1.pdf
          mv hw2/main.pdf build/solutions2.pdf

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
